[package]
name = "confy"
version = "0.2.0"
authors = ["Katharina Fey <kookie@spacekookie.de>"]

[dependencies]
serde = "1.0"
toml = "0.4"
directories = "0.10.0"
serde_derive = { version = "1.0", optional = true }

[features]
sd = ["serde_derive"]

[[example]]
name = "simple"
required-features = ["sd"]
