[package]
name = "confy"
version = "0.2.0"
authors = ["Katharina Fey <kookie@spacekookie.de>"]
description = "Boilerplate-free configuration management"
license = "MIT/X11 OR Apache-2"
documentation = "docs.rs/confy"
repository = "https://github.com/rust-clique/confy"

[dependencies]
serde = "1.0"
toml = "0.4"
directories = "0.10.0"
serde_derive = { version = "1.0", optional = true }

[features]
sd = ["serde_derive"]

[[example]]
name = "simple"
required-features = ["sd"]
